stages:
  - build
  - deploy

variables:
  DOCKER_USERNAME: alexeykarakcheev
  DOCKER_IMAGE: sppd-svc

build_backend:
  stage: build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_USERNAME/$DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_USERNAME/$DOCKER_IMAGE:latest
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
    
  only:
    - master

deploy:
  image: alpine/k8s:1.27.4
  stage: deploy
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
    - chmod +r ~/.kube/config
  script:
    # - cat ~/.kube/config
    # - kubectl config current-context
    # - kubectl cluster-info
    - kubectl apply -f k8s --request-timeout=30s

  only:
    - master

