apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "password"
  POSTGRES_PASSWORD: "password"
  REDIS_PASS: "password"
  MAIL_USERNAME: "fjk2003@yandex.ru"
  MAIL_PASSWORD: "zuuhmyrzyomzkceu"

